### ISSUE TITLE
How to extend the custom method?

### ISSUE THREAD

**Issue by maiguangyang** [novacloudcz/graphql-orm#19]
Hello:
I would like to ask, after the generated code, I want to expand a user login method, how to operate, is there an example?
Or if you want to extend other custom methods, what should you do?
Thanks!

**Comment by jakubknejzlik** [comment]
Hello @maiguangyang , I've just finished stuff related to Your question. Now it's possible to create custom fields using type extensions. Eg.:

```
type Company {
  name: String!
}
extend type Company {
  uppercaseName: String!
}
```

and then you implement the resolver in `src/resolver.go` by adding:
```
func (r *CompanyResolver) UppercaseName(ctx context.Context, obj *gen.Company) (string, error) {
	return strings.ToUpper(obj.Name), nil
}
```

The same applies to Query type. Please check the [example repository](https://github.com/novacloudcz/graphql-orm-example) for more details.
