### ISSUE TITLE
gen/generated.go:2236:4: expected ';', found directive2 (and 4346 more errors)

### ISSUE THREAD

**Issue by maiguangyang** [novacloudcz/graphql-orm#2]
![image](https://user-images.githubusercontent.com/22783048/60605451-1f086f80-9dec-11e9-910b-0bc7a1a3759f.png)

gen/generated.go:2236:4: expected ';', found directive2 (and 4346 more errors)

**Comment by jakubknejzlik** [comment]
Hi @maiguangyang, the generated.go is created by gqlgen, would it be possible for you to share the model.graphql or reproduce it and share it for example in repo?

**Comment by maiguangyang** [comment]
I used 2 custom instructions and it changed.

type User {
	email: String @validator(valid: "email", required: "true") @relationship(inverse:"assignee")
	firstName: String
	lastName: String
}

**Comment by jakubknejzlik** [comment]
I'm not able to replicate this. Specifically when adding relationship to `email` field I get this error:
```
Generating contents from model.graphql ...
template: gen/models.go:20:43: executing "gen/models.go" at <$rel.ModelTags>: error calling ModelTags: Object with name String not found in model
exit status 1
```
which is due to the fact, that String is not entity.

I also tried defining multiple directives with no issues, you can check the results in these commits:
https://github.com/novacloudcz/graphql-orm-example/commits/feature/test-custom-directive

Do you have gqlgen on lastest version? Could you post the whole example with generated code?

**Comment by maiguangyang** [comment]
> 我无法复制这个。特别是在向`email`字段添加关系时，我收到此错误：
> 
> ```
> Generating contents from model.graphql ...
> template: gen/models.go:20:43: executing "gen/models.go" at <$rel.ModelTags>: error calling ModelTags: Object with name String not found in model
> exit status 1
> ```
> 
> 这是因为String不是实体。
> 
> 我也试过定义多个指令没有问题，你可以检查这些提交中的结果：[https](https://github.com/novacloudcz/graphql-orm-example/commits/feature/test-custom-directive)：
> [//github.com/novacloudcz/graphql-orm-example/commits/feature/test-custom-directive](https://github.com/novacloudcz/graphql-orm-example/commits/feature/test-custom-directive)
> 
> 你有最新版本的gqlgen吗？你能用生成的代码发布整个例子吗？


Hello!
I cloned the feature/test-custom-directive branch of github.com/novacloudcz/graphql-orm-example.
Use go mod to install dependencies. Run the make run command to start normally.

**But using make generate to regenerate model.graphql, the following error is reported:**

[root@saas graphql-orm-example]# make generate
Go run github.com/novacloudcz/graphql-orm
Go: finding github.com/inloop/goclitools latest
Go: finding github.com/graphql-go/graphql/language/ast latest
Go: finding github.com/graphql-go/graphql/language/kinds latest
Go: finding github.com/graphql-go/graphql/language/parser latest
Go: finding github.com/graphql-go/graphql/language/printer latest
Go: finding github.com/graphql-go/graphql/language latest
Go: finding github.com/skratchdot/open-golang/open latest
Go: finding github.com/skratchdot/open-golang latest
Go: finding github.com/howeyc/gopass latest
Generating contents from model.graphql ...
Running gqlgen generator...
Gofmt failed on generated.go: /data/wwwroot/graphql-orm-example/gen/generated.go:3273:4: expected ';', found directive2 (and 5390 more errors)

**Run make run again to report the following error:**
[root@saas graphql-orm-example]# make run
DATABASE_URL=sqlite3://test.db PORT=8080 go run *.go
# github.com/novacloudcz/graphql-orm-example/gen
Gen/generated.go:3273:4: syntax error: unexpected directive2 at end of statement
Gen/generated.go:3284:3: syntax error: non-declaration statement outside function body
Make: *** [run] Error 2


![image](https://user-images.githubusercontent.com/22783048/60731351-edbdaa00-9f79-11e9-87be-829d73756bdd.png)

**Comment by jakubknejzlik** [comment]
What gqlgen version do you have installed?
You can check it by running ```cd $GOPATH/src/github.com/99designs/gqlgen && git log -p -1```

Could you try to update it to the latest version by running ```go get -u github.com/99designs/gqlgen```?

**Comment by maiguangyang** [comment]
> What gqlgen version do you have installed?
> You can check it by running `cd $GOPATH/src/github.com/99designs/gqlgen && git log -p -1`
> 
> Could you try to update it to the latest version by running `go get -u github.com/99designs/gqlgen`?

[root@saas gqlgen]# cd $GOPATH/src/github.com/99designs/gqlgen && git log -p -1
commit 414a4d3414b2b5856851816f0152980098f7b3ab
Merge: 21b6511 4d1484b
Author: Luke Cawood <luke.cawood@99designs.com>
Date:   Tue Jul 2 17:00:24 2019 +1000

    Merge pull request #771 from sunfmin/master
    
    Fix doc for how to use @goField directives forceResolver option

**Comment by jakubknejzlik** [comment]
Huh...honestly I’m running out of ideas what could be the difference between our setups :-/

**Comment by jakubknejzlik** [comment]
@maiguangyang did you manage to solve this?

**Comment by maiguangyang** [comment]
@jakubknejzlik 
directive @validator(valid: String!, required: String!) on MUTATION | QUERY | FIELD
directive @validator2(valid: String!, required: String!) on MUTATION | QUERY | FIELD

Solved, it’s my intention to use it like this.

**Comment by jakubknejzlik** [comment]
Just FYI as this may be related, I just pushed commit with changes that remove @relationship directive from final schema as it was causing some issues in combination gqlgen in some cases.
