### ISSUE TITLE
master latest code generation error

### ISSUE THREAD

**Issue by maiguangyang** [novacloudcz/graphql-orm#38]
```
Generating contents from model.graphql ...
Running gqlgen generator in gen ...
schemaconfig: schema.graphql:16: expected at least one definition, found }
exit status 3
exit status 1
exit status 1
```

![image](https://user-images.githubusercontent.com/22783048/64956781-f9a0e300-d8bd-11e9-849c-1d9679d74427.png)

![image](https://user-images.githubusercontent.com/22783048/64956793-0291b480-d8be-11e9-94fb-e828176393ec.png)

![image](https://user-images.githubusercontent.com/22783048/64956811-0cb3b300-d8be-11e9-901a-99d503f2e02a.png)

**Comment by jakubknejzlik** [comment]
Hello @maiguangyang, master version has updated requirements for model schema. Each entity has to be marked with `@entity` and each column with `@column` as can be seen here:
https://github.com/novacloudcz/graphql-orm-example/blob/master/model.graphql
