### ISSUE TITLE
use relationship create and update are reported incorrectly

### ISSUE THREAD

**Issue by maiguangyang** [novacloudcz/graphql-orm#4]
![image](https://user-images.githubusercontent.com/22783048/61763664-bd468e80-ae08-11e9-829e-89a441b50777.png)

![image](https://user-images.githubusercontent.com/22783048/61763675-cafc1400-ae08-11e9-907f-45dc3f1dd8d2.png)

![image](https://user-images.githubusercontent.com/22783048/61762957-3d1f2980-ae06-11e9-8db2-4fc60771acc4.png)

![image](https://user-images.githubusercontent.com/22783048/61762999-5aec8e80-ae06-11e9-8fba-b3125c157443.png)

https://github.com/novacloudcz/graphql-orm-example

use relationship create and update are reported incorrectly.

What is the correct operation?

**Comment by jakubknejzlik** [comment]
@maiguangyang your mutation is correct, the bug is in the `graphql-orm`. Thanks for letting me know, please check the latest version (fyi the code needs to be regenerated).
