### ISSUE TITLE
assignment mismatch: 2 variables but client.Send returns 3 values

### ISSUE THREAD

**Issue by abinash-mlbd** [novacloudcz/graphql-orm#55]
After running below command
`go run github.com/novacloudcz/graphql-orm init`
I am getting this error message 
`# github.com/novacloudcz/graphql-orm/events
../../../github.com/novacloudcz/graphql-orm/events/controller.go:52:13: assignment mismatch: 2 variables but client.Send returns 3 values`

Using go version : go1.13.4 linux/amd64

**Comment by jakubknejzlik** [comment]
hi @abinash-mlbd, are you using go modules? There's been an update for CloudEvents and unfortunately it's currently not possible to use the latest version. The go.mog contains fix to v0.8.0.

If you are running the command inside $GOPATH, could you try to enable the go modules?
```
GO111MODULE=on go run github.com/novacloudcz/graphql-orm init
```

_Note: you'll probably have to manually specify the package name_

**Comment by abinash-mlbd** [comment]
hi @jakubknejzlik, thanks for your quick reply.
Yes, I am running command inside $GOPATH. After enabled the go modules, it's working.

**Comment by jakubknejzlik** [comment]
That's good to know. I've updated README to reflect this information. Thank you :-)
