### ISSUE TITLE
How do I communicate between multiple projects?

### ISSUE THREAD

**Issue by maiguangyang** [novacloudcz/graphql-orm#63]
How do I communicate between multiple projects?
For example, I have two projects, A and B. In Project A, I want to query the data of Project B. How can I do this? Is there an example?

**Comment by jakubknejzlik** [comment]
Hi @maiguangyang, 
there are multiple ways to communicate between the projects. It depends on the specific cases. We are using two ways:

1) schema stitching/federation using Apollo Federation (for example using this image https://github.com/graphql-services/graphql-gateway) for cases when we need to combine data between multiple services
2) for more specific cases (especially mutations) we are sending requests directly to generated GraphQL api.  There are multiple approaches like generating client, building requests directly...we are using small library, but it's not yet official: https://github.com/graphql-services/go-saga/tree/master/graphqlorm
