### ISSUE TITLE
github.com/99designs/gqlgen The latest version (v0.11.1) reports an error

### ISSUE THREAD

**Issue by maiguangyang** [novacloudcz/graphql-orm#65]
Update github.com/99designs/gqlgen to the latest version (v0.11.1) and run make generate to report an error.
Take a look and updated the github.com/vektah/gqlparser package to github.com/vektah/gqlparser/v2

Following is github.com/99designs/gqlgen v0.9.1 run
![image](https://user-images.githubusercontent.com/22783048/74804388-12a13a80-531b-11ea-8cb8-b7a8f67cfb2d.png)

Following is github.com/99designs/gqlgen v0.11.1 run
![image](https://user-images.githubusercontent.com/22783048/74804422-306e9f80-531b-11ea-8e74-121c9f2969fb.png)

**Comment by jakubknejzlik** [comment]
Thanks @maiguangyang for notice. As they already stated in release:
```
As we start to approach 1.0 we are going to be breaking a few interfaces to make sure things are right.
```

But I hope it should not be as bad as it sounds :-)
