### ISSUE TITLE
gorm tags for e.g. default values

### ISSUE THREAD

**Issue by wiemann** [novacloudcz/graphql-orm#66]
I would like to add gorm tags for defining default values for columns to be used when automigrating.

http://gorm.io/docs/create.html#Default-Values

**Comment by jakubknejzlik** [comment]
Hello @wiemann , pleaseHello @wiemann , please check the latest version where default value has been added to `@column` directive. 
I've been thinking about adding generic tags for gorm too (eg. `@column(form:...)`), but I'm not sure if it's good idea to make direct dependency on gorm.
Did You case specifically about default value or is there something else from gorm tags?

**Comment by wiemann** [comment]
Looks good, thanks!
