### ISSUE TITLE
init failed

### ISSUE THREAD

**Issue by shynome** [novacloudcz/graphql-orm#70]
### Steps

- `mkdir gqlorm && cd gqlorm`
- `go mod init gqlorm`
- `graphql-orm init`

then it panic:

```log
Initializing project in . ...
Generating contents from [model.graphql] ...
Appending content from model file model.graphql
Running gqlgen generator in gen ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8961bc]

goroutine 1 [running]:
github.com/99designs/gqlgen/codegen/config.(*TypeReference).IsPtr(...)
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/codegen/config/binder.go:207
github.com/99designs/gqlgen/codegen.(*builder).buildField(0xc0006bbb20, 0xc000532280, 0xc000313260, 0x0, 0xef46e0, 0xc00090d900)
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/codegen/field.go:70 +0x35c
github.com/99designs/gqlgen/codegen.(*builder).buildObject(0xc0006bbb20, 0xc00031a600, 0x0, 0x0, 0x1)
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/codegen/object.go:73 +0x4a4
github.com/99designs/gqlgen/codegen.BuildData(0xc0002aa000, 0xafc640, 0xef3658, 0x0)
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/codegen/data.go:68 +0x478
github.com/99designs/gqlgen/api.Generate(0xc0002aa000, 0x0, 0x0, 0x0, 0x0, 0x20)
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/api/generate.go:72 +0x361
github.com/99designs/gqlgen/cmd.glob..func1(0xc000282240, 0xc000292200, 0x0)
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/cmd/gen.go:38 +0x93
github.com/urfave/cli/v2.(*App).RunContext(0xc000290000, 0xb07d20, 0xc000024100, 0xc0000201e0, 0x1, 0x1, 0x0, 0x0)
        ~/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:311 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
        ~/go/pkg/mod/github.com/urfave/cli/v2@v2.1.1/app.go:211
github.com/99designs/gqlgen/cmd.Execute()
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/cmd/root.go:41 +0x1f1
main.main()
        ~/go/pkg/mod/github.com/99designs/gqlgen@v0.12.2/main.go:8 +0x20
exit status 2
exit status 1
```

**Comment by jakubknejzlik** [comment]
Hello @shynome , thanks for reporting this issue. It's related to https://github.com/novacloudcz/graphql-orm/issues/65.
As hotfix please try to update `gqlgen` to `v0.10.2` before running the `graphql-orm init`:
```
github.com/99designs/gqlgen v0.10.2
```

Unfortunatelly I didn't have time to add support for changes to latest gqlgen, but the initialization is definitely worth fixing :)

**Comment by shynome** [comment]
Thanks your reply, but change `go.mod` file is not working. I think I should wait more time until this problem is resolved

**Comment by jakubknejzlik** [comment]
Would You mind sharing more information about Your environment? Namely:

1. go version
1. content of `go.mod` before running `graphql-orm init`

**Comment by jakubknejzlik** [comment]
@shynome I see the confusion now...on my side :) . By running `graphql-orm init` You are running graphql-orm outside of go modules. Running the full command seems to be working and installs dependencies in proper version:
```
mkdir gqlorm && cd gqlorm
go mod init gqlorm
go run github.com/novacloudcz/graphql-orm init
```

I also released v0.4.14 which updates few dependencies and remove some unnecessary initialization steps. Feel free to reopen this issue if Your problem persists 👍

**Comment by shynome** [comment]
go version
```
go version go1.14 linux/amd64
```

new error when run step `go run github.com/novacloudcz/graphql-orm init` 
```
Initializing project in . ...
sh: 1: set: Illegal option -o pipefail
exit status 2
exit status 1
```

**Comment by jakubknejzlik** [comment]
Not sure what version of bash You have, but probably the `set -o pipefail` isn't supported. I'm trying to switch the basic commands to plain bash without `set -o pipefail` command.

**Comment by shynome** [comment]
```
Initializing project in . ...
sh: 1: goimports: not found
exit status 127
```
but change `sh` to `bash` make it work, it seems `sh` don't read `$PATH` in `~/.profile`

**Comment by jakubknejzlik** [comment]
Updated to bash so only the `set -o pipefail` is removed. Also new vesion `v0.4.15` is created.

**Comment by shynome** [comment]
it is working !
